- pkgs/build-support/mk-epics-package.nix
- pkgs/epnix/epics-base/default.nix
causes issues with `nix develop`, see nix issue 7265
> mkEpicsPackages,epics-base: remove usage of passAsFile

- pkgs/build-support/mk-epics-package.nix
> mkEpicsPackage: properly fix Perl shebangs

- ioc/modules/outputs.nix
Previously, if the target directory existed, EPNix copied apps and iocBoot folders in the wrong place.
cc @agaget for review.
> ioc/outputs: fix copying of apps and iocBoot folders

- ioc/modules/checks.nix
- templates/top/flake.nix
this simplifies parametrized tests
this is now possible:
``` nix
checks.imports = [
(import ./checks/common.nix "epics-base3")
(import ./checks/common.nix "epics-base7")
];
```
cc @stephane-cea, since you needed this to test an support module for multiple epics-base versions.
> Checks imports

- flake.nix
- pkgs/default.nix
this enables easier overriding of packages, like this:
```nix
nixpkgs.overlays = [
(final: prev: {
epnix = prev.epnix.extend (final: prev: {
epics-base7 = prev.epics-base7.overrideAttrs (oldAttrs: {
patches = oldAttrs.patches ++ [ ./my.patch ];
});
});
})
];
```
cc @stephane-cea since you might use this feature for overriding epics-base. The old method should still work.
> pkgs: make package sets extensible

- ioc/modules/nixos-integration.nix
sometimes `procServ` exits cleanly, even though the IOC was killed by a signal (e.g. `SIGSEGV`). The IOC should restart in that case.
> ioc/modules/nixos-integration: change Restart systemd option to always

- nixos/modules/phoebus/local-kafka.nix
documentation recommends changing `extraProperties`, which overrides the properties defined here,
which makes Kafka complains that the replication factor can't be applied.
cc @lcaouen for review.
> nixos/local-kafka: always configure replication factor

- ioc/modules/common.nix
- ioc/modules/outputs.nix
- lib/default.nix
- lib/evaluation.nix
- templates/top/flake.nix
Before this PR, this was only supported to import an EPNix top as support module by importing its pre-configured package. This meant that it was annoying to have the same version of its dependencies (and epics-base refuses if there are different versions), and it was near impossible to setup cross-compilation with an EPNix support module.
This PR solves everything.
Best viewed commit by commit.
See the `templates/top` commit for how to use it, and how to update your `flake.nix` files.
> Fix support imports and exports

- nixos/tests/phoebus/save-and-restore.py
- pkgs/epnix/tools/phoebus/deps/default.nix
This upgrades Phoebus client, alarm-logger, alarm-server, archive-engine, olog, pva, save-and-restore, and scan-server.
With a fix, apparently the default base URL for Phoebus save-and-restore changed from `http//localhost:8080/` to `http//localhost:8080/save-restore/`
cc @lcaouen
> phoebus: 4.7.2 -> 4.7.3

- .github/workflows/book-gh-pages.yml
- .github/workflows/editorconfig.yml
- .github/workflows/formatting.yml
Because tags can be changed, they are a security risk. Using the commit hash is safer.
See: https://github.com/suzuki-shunsuke/pinact
> github: update actions, pin them with pinact

- lib/maintainers/maintainer-list.nix
- pkgs/default.nix
- pkgs/epnix/support/devlib2/default.nix
- pkgs/epnix/support/mrfioc2/default.nix
Using of the standard driver, customs modifications from CEA will be included at one point one day. It is not necessary for standard using.
In draft, because it needs to be tested with hardware.
> add mrfioc2 and devlib2 support

- lib/maintainers/maintainer-list.nix
- pkgs/default.nix
- pkgs/epnix/support/adsDriver/default.nix
- pkgs/epnix/support/autoparamDriver/default.nix
Add adsDriver (https://epics.cosylab.com/documentation/adsDriver/) and autoParamDriver (dependency, https://epics.cosylab.com/documentation/autoparamDriver)
I'm not sure what is meant with the mandatory varname attribute (fairly new to EPICS) so I'm not sure if I got those correct, would like review on that.
Added myself as maintainer for these two.
> Add adsDriver and autoparamDriver

- lib/documentation.nix
lib.licenses.free for example doesn't have an URL
Fixes #46
> lib/documentation: don't require licenses to have an URL

- .gitlab-ci.yml
So that on our GitLab, pushing to a branch cancel running jobs from previous commits. Should make our poor, poor build server use less resources.
> gitlab-ci: make pipeline/jobs interruptible

- pkgs/epnix/tools/archiver-appliance/default.nix
Archiver appliance got its own github namespace, which causes our build to fail.
> Archiver appliance: move to new owner

- pkgs/default.nix
- pkgs/epnix/support/twincat-ads/default.nix
Add ESS ADS driver for Beckhoff TwinCAT communication.
https://gitlab.esss.lu.se/epics-modules/epics-twincat-ads
> Adding ads driver support

- ioc/tests/default.nix
- ioc/tests/pyepics/default.nix
- pkgs/default.nix
- pkgs/epnix/python-modules/pyepics/default.nix
and make it so that python packages work for any python version.
> pyepics: init at 3.5.6

- pkgs/default.nix
- pkgs/epnix/epics-base/default.nix
Most relevant for this project: the fortify-source issue was worked around, will probably be fixed in the next minor version.
Do we want to keep in the fortify3 disable for backwards source compatibility or remove it for forwards compatibility?
> epics-base7: 7.0.8 -> 7.0.8.1

- .github/workflows/update-flake-lock.yml
So that we stay up-to-date, even inside a release branch.
This will create a PR weekly (or on demand) that proposes the result of a `nix flake update --commit-lock-file` for the EPNix repository, on each release branch.
> github: init Update flake.lock action

- pkgs/default.nix
- pkgs/epnix/tools/phoebus/client/default.nix
- pkgs/epnix/tools/phoebus/client/fix-python-path.patch
Upstream defaults to /usr/bin/python3, which doesn't exist on NixOS
Fixes #100
And some minor cleanup
> phoebus-client: hardcode Python path for the console view

- ioc/modules/nixos-integration.nix
- nixos/modules/ca-gateway.nix
- nixos/modules/phoebus/alarm-logger.nix
- nixos/modules/phoebus/olog.nix
- nixos/modules/phoebus/save-and-restore.nix
- pkgs/epnix/tools/ca-gateway/default.nix
- pkgs/epnix/tools/lewis/default.nix
- pkgs/epnix/tools/phoebus/alarm-logger/default.nix
- pkgs/epnix/tools/phoebus/archive-engine/default.nix
- pkgs/epnix/tools/phoebus/client/default.nix
- pkgs/epnix/tools/phoebus/pva/default.nix
- pkgs/epnix/tools/phoebus/save-and-restore/default.nix
- pkgs/epnix/tools/phoebus/scan-server/default.nix
- pkgs/epnix/tools/procServ/default.nix
Makes things nicer overall. No need to `"${pkgs.epnix.procServ}/bin/procServ"` when you can just `lib.getExe pkgs.epnix.procServ`
Fixes #62
> Use `meta.mainProgram` and `lib.getExe`

- flake.nix
- pkgs/default.nix
- pkgs/epnix/kernel-modules/mrf/default.nix
- pkgs/tests/default.nix
Pinging @agaget for testing it on real hardware.
To add the module, make sure you [import EPNix](https://github.com/epics-extensions/EPNix/blob/master/doc/nixos/guides/_pre-requisites.md), and you should be able to set `boot.kernelModules = ["mrf"];`
I'll have to add that exact documentation later.
> linuxPackages.mrf: init at 2.6.0

- .github/workflows/editorconfig.yml
- .github/workflows/formatting.yml
This enables jobs to run even for new contributors, because the definition of the job will be from the base branch of the PR, instead of the PR's latest commit.
So contributors can't modify the GitHub workflow and run whatever they want by just opening a PR.
> github: run jobs in pull_request_target

- docs/ioc/user-guides/index.rst
- docs/ioc/user-guides/testing/index.rst
- docs/ioc/user-guides/testing/unit-testing.rst
- ioc/modules/common.nix
- nixos/modules/archiver-appliance.nix
Document `gtest` first as a way to encourage people to use it, as `gtest` is more complete and well-known.
Still document epics-base based unit tests if people don't want / can't use the `gtest` support module.
> Unit testing documentation

- docs/index.rst
- docs/nixos-services/tutorials/archiver-appliance.rst
- docs/nixos-services/user-guides/pre-requisites.rst
- flake.lock
- flake.nix
- pkgs/default.nix
- pkgs/docs/default.nix
- pkgs/epnix/kernel-modules/mrf/default.nix
- pkgs/epnix/support/twincat-ads/default.nix
- pkgs/epnix/support/twincat-ads/fix-missing-header.patch
- pkgs/epnix/tools/open62541_1_3/default.nix
- pkgs/epnix/tools/phoebus/deps/default.nix
- templates/top/flake.nix
and related changes to documentation and templates, and to the Phoebus deps output hash.
Currently draft, because the opcua EPICS module is currently not compatible with `libopen62541 >= 1.4.0`
> upgrade NixOS 23.11 -> 24.05

- docs/nixos-services/user-guides/phoebus-alarm.rst
- docs/nixos-services/user-guides/phoebus-save-and-restore.rst
- docs/release-notes/2405.rst
- nixos/modules/phoebus/olog.nix
- nixos/modules/phoebus/save-and-restore.nix
- nixos/tests/phoebus/olog.nix
- nixos/tests/phoebus/save-and-restore.nix
For Phoebus Olog, and Phoebus save-and-restore
See https://github.com/epics-extensions/EPNix/issues/75, https://github.com/epics-extensions/EPNix/issues/54, follow-up of https://github.com/epics-extensions/EPNix/pull/60
Specify in documentation that enabling ElasticSearch needs to be done
only once.
> Don't automatically enable elasticsearch

- nixos/modules/phoebus/alarm-logger.nix
- nixos/tests/phoebus/alarm.nix
- nixos/tests/phoebus/alarm.py
phoebus-alarm-logger does not forward the given configuration to SpringBoot, so we use an environment variable to forward it ourselves.
this caused options like "server.port" to be ignored, since they are SpringBoto specific.
Use the "server.port" option in the test to test regressions.
fixes #56
> nixos/phoebus-alarm-logger: forward configuration to SpringBoot

- pkgs/epnix/support/StreamDevice/default.nix
According to the release notes in [the tags](https://github.com/paulscherrerinstitute/StreamDevice/tags), no backward incompatible changes
>  support.StreamDevice: 2.8.24 -> 2.8.26 

- templates/top/.gitlab-ci.yml
Manpage and pages build support have been dropped in EPNix 24.05 (I think).
So the associated GitLab stages will cause the CI to fail by default.
This PR simply proposes to remove the manpage and pages CI build stages.
> fix: remove manpage and pages stages from template CI

- .editorconfig
- ioc/modules/common.nix
- pkgs/docs/default.nix
Fix formatting after #198 
Currently the GitHub actions are messed up (should be fixed by #197), so we didn't catch the formatting errors.
> Fix formatting

- .github/workflows/update-flake-lock.yml
Older releases are not supported upstream, so the nixpkgs input shouldn't update, most of the time
> github/update-flake-lock: only update master and latest release

- .github/workflows/zizmor.yml
This should give us some "Code scanning" alerts when GitHub workflows are implemented poorly.
Note that the backport action will trigger an alert, due to the fact that we have to use `pull_request_target`, which is inherently hard to use securely.
Inspired by:
https://woodruffw.github.io/zizmor/usage/#use-in-github-actions
> github/zizmor: add action that checks actions security

- docs/release-notes/2411.rst
- pkgs/epnix/support/modbus/default.nix
and document the upstream change in the `modbus.dbd` -> `modbusApp.dbd`
release notes:
- https://github.com/epics-modules/modbus/blob/master/RELEASE.md#r3-3-december-7-2023
- https://github.com/epics-modules/modbus/blob/master/RELEASE.md#r3-4-december-1-2024
> support/modbus: 3-2 -> 3-4

- nixos/tests/phoebus/alarm.py
In the current config Kafka only listens to IPv4, but when we use `kcat server:9092 ...`, sometimes `server` gets resolved to the IPv6 of the VM, which makes the test fail.
> nixos/tests/phoebus-alarm: use IPv4 when querying Kafka

- docs/_static/multi-version.css
- docs/_templates/multi-version.html
- docs/conf.py
Goes with #216, but applied to the nixos-24.05 branch.
> docs: support multiple versions

- .github/workflows/book-gh-pages.yml
- docs/_static/multi-version.css
- docs/_templates/multi-version.html
- docs/conf.py
- pkgs/ci-scripts/build-docs-multiversion.nix
- pkgs/default.nix
This PR changes the way we build the documentation.
Instead of only building the documentation of `master`, it builds the documentation of `master` *and* `nixos-24.05`, and pushes both, respectively in the `dev` and `nixos-24.05` directory.
This means that URLs will change. For example, the URL:
https://epics-extensions.github.io/EPNix/nixos-services/index.html
becomes
https://epics-extensions.github.io/EPNix/dev/nixos-services/index.html
or
https://epics-extensions.github.io/EPNix/nixos-24.05/nixos-services/index.html
But this also means that URLs will be less likely to break in the future.
Note to self, after this PR is merged, I need to backport the commit `docs: support multiple versions`, but *making sure the `release` variable is correct in `docs/conf.py`*.
> Multiversionned docs

- .github/workflows/book-gh-pages.yml
Messed up again, because the main branch is named "main" on my test repo, but "master" in EPNix -_-"
> github/book-gh-pages: fix master branch name

- ioc/tests/cross/default.nix
- ioc/tests/default.nix
Now faster since we don't start a whole VM for running just one command,
and add the aarch64 platform, since it's so common these days.
> Better cross-compilation tests

- docs/release-notes/2411.rst
- nixos/modules/phoebus/olog.nix
- nixos/tests/phoebus/olog.nix
To prevent having to compile MongoDB, which requires a lot of resources
> nixos/phoebus-olog: use FerretDB intead of MongoDB

- .github/workflows/update-flake-lock.yml
- docs/conf.py
- docs/index.rst
- docs/nixos-services/tutorials/archiver-appliance.rst
- docs/nixos-services/user-guides/pre-requisites.rst
- flake.lock
- flake.nix
- nixos/modules/channel-finder/recceiver.nix
- pkgs/default.nix
- pkgs/docs/default.nix
- pkgs/epnix/tools/channel-finder/recceiver/default.nix
- pkgs/epnix/tools/lewis/default.nix
- pkgs/epnix/tools/phoebus/client/default.nix
- pkgs/epnix/tools/phoebus/deps/default.nix
- pkgs/epnix/tools/phoebus/olog/default.nix
- pkgs/tests/default.nix
- templates/top/flake.nix
See #225 for the upgrade process documentation.
> Upgrade NixOS 24.05 -> 24.11

- pkgs/default.nix
not needed since the NixOS 24.11 upgrade
> pkgs/default: remove unneeded setuptools-dso override

- docs/development/guides/index.rst
- docs/development/guides/release-process.rst
- docs/index.rst
I thought it was a nice thing to document, along the process of upgrading to NixOS 24.11
> docs: document the EPNix release process

- .github/workflows/book-gh-pages.yml
- .github/workflows/build-checks.yml
- flake.lock
- flake.nix
Enables us to see the result of checks directly on GitHub.
It's really not optimized, since it will compile for example epics-base for each check that needs it (~20 times), but it should be a nice stopgap solution until we deploy our own public CI and cache server.
~~Also add `x86_64-darwin` to supported system, in case we want to support MacOS developers.~~
It seems there's some work to do for MacOS support…
> GitHub build checks

- pkgs/default.nix
- pkgs/epnix/epics-base/default.nix
re-enabled the fortify3 compilation option,
since it was fixed upstream
> epics-base: 7.0.8.1 -> 7.0.9

- pkgs/epnix/tools/phoebus/alarm-logger/default.nix
- pkgs/epnix/tools/phoebus/alarm-server/default.nix
- pkgs/epnix/tools/phoebus/archive-engine/default.nix
- pkgs/epnix/tools/phoebus/client-unwrapped/default.nix
- pkgs/epnix/tools/phoebus/deps/default.nix
- pkgs/epnix/tools/phoebus/pva/default.nix
- pkgs/epnix/tools/phoebus/save-and-restore/default.nix
- pkgs/epnix/tools/phoebus/scan-server/default.nix
Using this flag instead skips test compilation, which reduces build times by about 25% on my machine. The build times for phoebus get kind of long on our gitlab runners (~15 minutes), so reducing it by a significant amount may be helpful.
Documentation does say that it is not recommended to use this flag, but especially for the phoebus-deps package, it seems unnecessary to compile the tests, when they are not even going to be ran. 
See also [the documentation](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#skip) and [this SO post](https://stackoverflow.com/questions/2593588/maven-skip-building-test-classes).
> Use maven.test.skip instead of skipTests for phoebus builds

- nixos/tests/phoebus/alarm.nix
- nixos/tests/phoebus/alarm.py
It appears that the check for the data still there after reboot was too soon, leading to a test that would fail quite regularly, but not always.
> Fix Phoebus alarm test flakiness

- docs/conf.py
- docs/nixos-services/options-reference/ioc-services.rst
- docs/nixos-services/user-guides/index.rst
- docs/nixos-services/user-guides/ioc-services.rst
- docs/release-notes/2505.rst
- lib/default.nix
- nixos/module-list.nix
- nixos/modules/iocs.nix
- templates/new-top/checks/simple.nix
- templates/new-top/flake.nix
Creates a NixOS module for declaring IOC services. It's based on `systemd.services`, but automatically configures `procServ` and some security isolation options.
The existing documentation and NixOS test are still using the old system, I'll update them in a subsequent PR.
> IOC service NixOS module

- README.md
- docs/index.rst
- docs/ioc/index.rst
Use the more official GitHub repo, we're now using the GitHub as source for the build anyway, see #260
> docs: remove mentions of epics-base's Launchpad repo

- docs/_vale/config/vocabularies/EPNix/accept.txt
- docs/nixos-services/options-reference/phoebus-save-and-restore.md
- docs/nixos-services/user-guides/channel-finder.md
- docs/nixos-services/user-guides/phoebus-save-and-restore.md
- docs/release-notes/2505.md
- nixos/modules/phoebus/alarm-logger.nix
- nixos/modules/phoebus/save-and-restore.nix
- nixos/tests/phoebus/alarm.py
- nixos/tests/phoebus/save-and-restore.ldif
- nixos/tests/phoebus/save-and-restore.nix
- nixos/tests/phoebus/save-and-restore.py
- pkgs/epnix/tools/phoebus/deps/default.nix
This Phoebus release includes the "In-memory preferences" contribution, which will enable us to have a Phoebus settings module (#38), to be done in another PR.
> phoebus: 4.7.3 -> 5.0.0

- nixos/modules/channel-finder/recceiver.nix
Previous description was a bad copy-paste.
New description is from the [RecCeiver demo.conf file].
[RecCeiver demo.conf file]: https://github.com/ChannelFinder/recsync/blob/1.6/server/demo.conf
> nixos/recceiver: fix addrlist option description

- pkgs/default.nix
The `docs` package is basically the same as the `book` package, but it builds the doc in `share/doc/epnix/html`,
as expected by the `build-docs-multiversion` script on master.
This allows us to build this older version of the documentation, and make it show up on the EPNix website.
> [nixos-23.11] pkgs/docs: create "alias" of the book package

- pkgs/default.nix
This is a backport of #336 for the branch nixos-23.05
The "docs" package is basically the same as the "book" package, but it builds the doc in "share/doc/epnix/html",
as expected by the "build-docs-multiversion" script on master.
This allows us to build this older version of the documentation, and make it show up on the EPNix website.
(cherry picked from commit 2da9df180b11c5e8a63732d0d89ad80d9e36b24f)
> [nixos-23.05] pkgs/docs: create "alias" of the book package

- .github/workflows/book-gh-pages.yml
- .github/workflows/build-checks.yml
- .github/workflows/editorconfig.yml
- .github/workflows/formatting.yml
- .github/workflows/update-flake-lock.yml
- .github/workflows/zizmor.yml
- docs/conf.py
- docs/development/guides/release-process.md
- docs/index.md
- flake.nix
- lib/ci.nix
- lib/default.nix
- lib/versions.nix
- pkgs/by-name/docs/package.nix
- pkgs/ci-scripts/by-name/build-docs-multiversion/package.nix
Try to define EPNix version information in a single place, as much as possible.
This means less work to do for EPNix releases, because less places to update.
- For GitHub actions, we dynamically generate a matrix job, instead of hardcoding
- For building the documentation website, the bash script now fetches the various EPNix versions by itself, instead of using the `actions/checkout` action
- Depends on #336 and its backport
- For documentation, we use [MyST's substitutions](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#substitutions-with-jinja2)
Things that I couldn't update:
- Code blocks in documentation (MyST substitutions doesn't work in code blocks)
- The `flake.nix` in Nix templates (from what I remember, it can't be generated)
I also changed the install nix …
> Factorize versions information

- docs/conf.py
- pkgs/docs/default.nix
Changes imported from master, for the branch nixos-24.11:
- Links point to the correct branch, not "master"
- Copyright has a sensible date
Fixes #287
> docs: fix source links and copyright

- docs/conf.py
The branch of these buttons is currently wrong on the `nixos-25.05` branch.
> docs: fix branch of "view / edit this page" buttons

- .github/workflows/docs-linkcheck.yml
> github/docs-linkcheck: fix workflow

- docs/conf.py
- lib/versions.nix
- pkgs/ci-scripts/by-name/build-docs-multiversion/package.nix
This needed building the documentation outside of the Nix sandbox, due to the internet connection requirement.
Also disables the build of the 23.11 and 23.05 EPNix version, because it caused issues with the "outside of the sandbox" thing. I don't think they have many users, in any case.
> docs: configure Intersphinx

- nixos/tests/phoebus/olog.nix
- pkgs/by-name/phoebus-olog/package.nix
Currently as draft, while we figure out the breaking changes.
The only one I know currently is the `/login` endpoint, which doesn't accept passing credentials through GET parameters anymore. You have to pass it as JSON in the request body.
@lcaouen do you know of any breaking change?
> phoebus-olog: 4.7.7 -> 5.0.4

- pkgs/by-name/phoebus-olog/fix-deps-reproducibility.patch
- pkgs/by-name/phoebus-olog/package.nix
The spring-boot-maven-plugin's version wasn't fixed, so Maven downloaded the version list from maven central and picked always the latest version,
which isn't reproducible since new versions are added over time.
> phoebus-olog: fix deps reproducibility

- docs/cheatsheet.md
- docs/contributing/guides/release-process.md
- docs/index.md
- docs/ioc/tutorials/integration-tests.md
- docs/ioc/tutorials/streamdevice.md
- docs/ioc/user-guides/testing/unit-testing.md
- docs/nixos-services/user-guides/ca-gateway.md
- docs/nixos-services/user-guides/channel-finder.md
- docs/nixos-services/user-guides/epics-environment.md
- docs/nixos-services/user-guides/index.md
- docs/nixos-services/user-guides/ioc-services.md
- docs/nixos-services/user-guides/phoebus-alarm.md
- docs/nixos-services/user-guides/phoebus-client.md
- docs/nixos-services/user-guides/phoebus-save-and-restore.md
- docs/nixos-services/user-guides/pre-requisites.md
- docs/nixos-services/user-guides/prerequisites.md
- docs/prerequisites.md
- docs/redirects.txt
- Rename "pre-requisites" to "prerequisites", because it's the correct word!
- Make the NixOS prerequisites its own, up front page
- Mention that the hostname must be consistent in the NixOS prerequisites
Fixes #403
> docs: better prerequisites
