epics-extensions/EPNix

LICENSE, NOTICE
=> Add license and copyright notice

pkgs/build-support/mk-epics-package.nix, pkgs/epnix/tools/procServ/default.nix
Also enable parallel building for `procServ`
=> mkEpicsPackage: don't manually make install

pkgs/epnix/tools/phoebus/deps/default.nix
4.7.2 was released: https://github.com/ControlSystemStudio/phoebus/releases/tag/v4.7.2
=> phoebus: 4.7.2-SNAPSHOT -> 4.7.2

pkgs/epnix/support/asyn/default.nix
https://github.com/epics-modules/asyn/releases/tag/R4-44-2
=> support/asyn: 4-44 -> 4-44-2

ioc/modules/base.nix, ioc/tests/default-ioc/default.nix, ioc/tests/default-ioc/top/.gitignore, ioc/tests/default-ioc/top/Makefile, ioc/tests/default-ioc/top/configure/CONFIG, ioc/tests/default-ioc/top/configure/CONFIG_SITE, ioc/tests/default-ioc/top/configure/Makefile, ioc/tests/default-ioc/top/configure/RELEASE, ioc/tests/default-ioc/top/configure/RULES, ioc/tests/default-ioc/top/configure/RULES.ioc, ioc/tests/default-ioc/top/configure/RULES_DIRS, ioc/tests/default-ioc/top/configure/RULES_TOP, ioc/tests/default-ioc/top/epnix.nix, ioc/tests/default-ioc/top/iocBoot/Makefile, ioc/tests/default-ioc/top/iocBoot/iocsimple/Makefile, ioc/tests/default-ioc/top/iocBoot/iocsimple/st.cmd, ioc/tests/default-ioc/top/simpleApp/Db/Makefile, ioc/tests/default-ioc/top/simpleApp/Db/simple.db, ioc/tests/default-ioc/top/simpleApp/Makefile, ioc/tests/default-ioc/top/simpleApp/src/Makefile, ioc/tests/default-ioc/top/simpleApp/src/simpleMain.cpp, ioc/tests/default.nix
=> Fix EPICS base selection

nixos/module-list.nix, nixos/modules/archiver-appliance.nix, nixos/tests/all-tests.nix, nixos/tests/archiver-appliance/default.nix, nixos/tests/archiver-appliance/test.db, nixos/tests/archiver-appliance/test_script.py, pkgs/default.nix, pkgs/epnix/tools/archiver-appliance/default.nix, pkgs/epnix/tools/archiver-appliance/fix-policies-shebang.patch, pkgs/epnix/tools/archiver-appliance/skip-release-notes.patch, pkgs/epnix/tools/jna/default.nix, pkgs/epnix/tools/mariadb_jdbc/default.nix
Package Archiver Appliance, add a NixOS module, and an integration test.
=> Archiver Appliance

pkgs/epnix/support/seq/default.nix
As said in the mailing list: https://epics.anl.gov/tech-talk/2023/msg01214.php
=> pkgs/seq: point to new project home

ioc/modules/devshell.nix, ioc/tests/support/StreamDevice/simple/mock-server/mock_server/__init__.py, ioc/tests/support/StreamDevice/simple/mock-server/pyproject.toml, pkgs/epnix/support/calc/default.nix
Various clean ups, found during development
=> Some cleanup

doc/_quarto.yml, doc/_vale/Vocab/EPNix/accept.txt, doc/nixos/guides/_pre-requisites.md, doc/nixos/guides/phoebus-alarm.md, nixos/modules/phoebus/alarm-server.nix
Added the email options, and some small fixes for the Phoebus Alarm Server NixOS module.
cc @achoqt for review
=> Phoebus Alarm docs single setup guide

doc/_quarto.yml, doc/nixos/guides/ca-gateway.md, lib/default.nix, lib/testing.nix, nixos/module-list.nix, nixos/modules/ca-gateway.nix, nixos/tests/all-tests.nix, nixos/tests/ca-gateway.nix, pkgs/default.nix, pkgs/epnix/tools/ca-gateway/default.nix, pkgs/epnix/tools/pcas/default.nix
Package the CA PV gateway, with also a NixOS module for configuring it as a systemd service, and a setup guide in the documentation.
cc @agaget & @stephane-cea for review
=> CA gateway

README.md
=> Fix readme after #25

ioc/tests/support/pvxs/ioc/default.nix, ioc/tests/support/pvxs/qsrv2/default.nix, ioc/tests/support/pvxs/standalone-server/default.nix, pkgs/default.nix, pkgs/epnix/epics-base/default.nix
Release notes for 7.0.8: https://github.com/epics-base/epics-base/blob/7.0/documentation/RELEASE_NOTES.md#epics-release-708
I think we mostly just wait that our tests on our internal GitLab passes.
=> epics-base: 7.0.7 -> 7.0.8

pkgs/default.nix, pkgs/epnix/support/busy/default.nix, pkgs/epnix/support/busy/fix-release.patch
=> add EPICS module support busy

nixos/modules/phoebus/alarm-server.nix, nixos/tests/phoebus/alarm.py, pkgs/epnix/tools/phoebus/alarm-server/default.nix
=> nixos/phoebus-alarm-server: put config in /etc, install package

pkgs/epnix/tools/phoebus/olog/default.nix
=> olog 4.7.7 + remove sed to build a valid jar

docs/ioc/user-guides/index.rst, docs/ioc/user-guides/mrf-devices.rst, lib/documentation.nix, lib/documentation/markdown.nix, pkgs/epnix/support/mrfioc2/default.nix
Follow up of #112
Added a little bit of Nix code to be able to make reference links to packages.
=> MRF documentation

README.md, flake.nix
=> Fix documentation links

.github/workflows/backport.yml, .github/workflows/book-gh-pages.yml, .github/workflows/editorconfig.yml, .github/workflows/formatting.yml, .github/workflows/update-flake-lock.yml
The backport action however still needs the credentials
=> github: don't persist checkout credentials by default

pkgs/epnix/support/calc/default.nix
=> support.calc: 3-7-4 -> 3-7-5

pkgs/epnix/support/sscan/default.nix
=> support.sscan: 2-11-5 -> 2-11-6

.github/workflows/book-gh-pages.yml, .github/workflows/editorconfig.yml, .github/workflows/formatting.yml
Some recommendations to apply, found thanks to [zizmor](https://woodruffw.github.io/zizmor/)
=> GitHub actions security

docs/conf.py, pkgs/docs/default.nix
This should lead to better referencing in search engines, and nicer "social media" sharing previews
=> docs: add opengraph metadata to HTML website

.github/workflows/book-gh-pages.yml, pkgs/ci-scripts/build-docs-multiversion.nix
=> docs: build version nixos-24.11 of the book

flake.lock, flake.nix, ioc/modules/common.nix
wasn't used in EPNix' repository
=> flake: remove poetry2nix

ioc/modules/base.nix, pkgs/epnix/epics-base/default.nix
- Removed some unused arguments, which should make the code a bit clearer
- Removed some Nix `with`, which are not recommended
- Expand on some cross-compilation comments
=> epics-base small refactoring

docs/cheatsheet.rst, docs/index.rst
No PDF for the cheatsheet yet, the way I wanted to integrate it uses additional experimental Nix features, which is causing CI issues both on GitHub and GitLab…
=> docs: init cheatsheet

.github/workflows/build-checks.yml
was upstreamed to the nix-quick-install action
=> github/build-checks: remove KVM setup bit

nixos/tests/all-tests.nix, nixos/tests/p4p.nix, pkgs/default.nix, pkgs/epnix/python-modules/p4p/default.nix
=> pythonPackages/p4p: init at 4.2.0

ioc/tests/pyepics/default.nix
Using `writePython3` makes the code slightly easier to read.
=> tests/pyepics: use writePython3 instead of python3.withPackages

docs/ioc/user-guides/private-repo-setup.rst, docs/nixos-services/tutorials/archiver-appliance.rst, lib/documentation.nix, pkgs/doc-support/psu-simulator/default.nix, pkgs/epnix/python-modules/softioc/default.nix, pkgs/epnix/support/seq/default.nix, pkgs/epnix/support/snmp/default.nix, pkgs/epnix/tools/archiver-appliance/default.nix, pkgs/epnix/tools/lewis/default.nix
Backport of #348, for the `nixos-24.11` branch.
=> Backport #348 to nixos-24.11

README.md, docs/development/guides/release-process.md, docs/ioc/user-guides/deprecations/migrating-from-modules-development.md, docs/ioc/user-guides/deprecations/migrating-from-modules-development/after-flake.nix, docs/ioc/user-guides/deprecations/migrating-from-modules-development/before-flake.nix, docs/nixos-services/tutorials/archiver-appliance.md, docs/nixos-services/user-guides/ioc-services.md, docs/nixos-services/user-guides/pre-requisites.md, docs/release-notes/2505.md, lib/versions.nix, templates/new-top/flake.nix, templates/top/flake.nix
- In the release notes:
- Add things that were missing (please tell me if I've forgotten things)
- Merge the "New features" and "Highlights" sections
- Follow the rest of the [Release process](https://epics-extensions.github.io/EPNix/dev/development/guides/release-process.html) guide
=> Prepare for release 25.05

pkgs/by-name/archiver-appliance/deps.json, pkgs/by-name/archiver-appliance/package.nix
JDK upgrade from 17 to 21 necessary since archiver-appliance 2.0.9
=> archiver-appliance: 2.0.7 -> 2.0.10

.github/workflows/docs-linkcheck.yml, .gitignore, docs/.gitignore, docs/conf.py, pkgs/by-name/docs/package.nix, pkgs/ci-scripts/by-name/docs-linkcheck/package.nix
Uses Sphinx builtin link checker
=> docs: check links in CI

docs/_static/tippy.css, docs/conf.py, pkgs/by-name/docs/package.nix, pkgs/python-modules/by-name/sphinx-tippy/fix-selector-quoting.patch, pkgs/python-modules/by-name/sphinx-tippy/package.nix
Show tips previews of pages when hovering over a local link.
=> docs: add sphinx-tippy extension

pkgs/support/by-name/asyn/package.nix, pkgs/support/by-name/calc/package.nix, templates/top/ioc.nix
Found during the writing of #380
=> various package fixes

nixos/tests/archiver-appliance/test_script.py, pkgs/by-name/archiver-appliance/deps.json, pkgs/by-name/archiver-appliance/package.nix
Fixed the test, due to the "never connected PVs" API being called to soon for archiver-appliance
=> archiver-appliance: 2.0.10 -> 2.1.0
